### PR TITLE
profiling: add new faults and use crt0_p.o when profiling

### PR DESCRIPTION
**Pull request by dlagneux-upmem**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Do not forget the associated test in `<dpu_tools>/endtests/documentation/exceptions_example`

**Comment by dlagneux-upmem** [comment]
> Do not forget the associated test in `<dpu_tools>/endtests/documentation/exceptions_example`

Yep, review is pending. Thx

**Comment by ghost** [comment]
I believe this PR could be closed?

**Comment by dlagneux-upmem** [comment]
> I believe this PR could be closed?

Yes

**Pull request closed without merging**
